### ISSUE TITLE
Improve README

### ISSUE THREAD

**Issue by pchampin** [maribelacosta/wikiwho#1]
Nice project!
It would be nice to better explain in your README the kind of inputfile that your program expect...
Can't wait to try it :)

**Comment by 0nse** [comment]
It expects an XML dump of Wikipedia pages with revisions. You can obtain a data dump (e.g. for the [English Wikipedia](https://dumps.wikimedia.org/enwiki/latest/)) or dump individual pages by using [this site](https://en.wikipedia.org/w/index.php?title=Special:Export&history).

However, I agree that this could also be mentioned in the README.
